

package com.concretepage.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Welcome", targetNamespace = "http://endpoint.concretepage.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Welcome {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWelcomeMsg", targetNamespace = "http://endpoint.concretepage.com/", className = "com.concretepage.endpoint.GetWelcomeMsg")
    @ResponseWrapper(localName = "getWelcomeMsgResponse", targetNamespace = "http://endpoint.concretepage.com/", className = "com.concretepage.endpoint.GetWelcomeMsgResponse")
    @Action(input = "http://endpoint.concretepage.com/Welcome/getWelcomeMsgRequest", output = "http://endpoint.concretepage.com/Welcome/getWelcomeMsgResponse")
    public String getWelcomeMsg(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}






























